# Generated by Django 2.0 on 2020-05-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lembrete', '0006_auto_20200511_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='conteudo',
            field=models.CharField(max_length=1000, verbose_name='Conteúdo'),
        ),
    ]
